DEF NUM_PLAYER_NAMES EQU 3

DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "JACK"

DEF GREENNAME1 EQUS "GREEN"
DEF GREENNAME2 EQUS "LEAF"
DEF GREENNAME3 EQUS "ALYSSA"

DEF YELLOWNAME1 EQUS "YELLOW"
DEF YELLOWNAME2 EQUS "DAMON"
DEF YELLOWNAME3 EQUS "ALEXYS"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "JOHN"
