; overworld sprites
; SpriteSheetPointerTable indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE                    ; $00
	const SPRITE_RED                     ; $01
	const SPRITE_BLUE                    ; $02
	const SPRITE_OAK                     ; $03
	const SPRITE_YOUNGSTER               ; $04
	const SPRITE_MONSTER                 ; $05
	const SPRITE_COOLTRAINER_F           ; $06
	const SPRITE_COOLTRAINER_M           ; $07
	const SPRITE_LITTLE_GIRL             ; $08
	const SPRITE_BIRD                    ; $09
	const SPRITE_MIDDLE_AGED_MAN         ; $0a
	const SPRITE_GAMBLER                 ; $0b
	const SPRITE_SUPER_NERD              ; $0c
	const SPRITE_GIRL                    ; $0d
	const SPRITE_HIKER                   ; $0e
	const SPRITE_BEAUTY                  ; $0f
	const SPRITE_GENTLEMAN               ; $10
	const SPRITE_DAISY                   ; $11
	const SPRITE_BIKER                   ; $12
	const SPRITE_SAILOR                  ; $13
	const SPRITE_COOK                    ; $14
	const SPRITE_BIKE_SHOP_CLERK         ; $15
	const SPRITE_MR_FUJI                 ; $16
	const SPRITE_GIOVANNI                ; $17
	const SPRITE_ROCKET                  ; $18
	const SPRITE_CHANNELER               ; $19
	const SPRITE_WAITER                  ; $1a
	const SPRITE_SILPH_WORKER_F          ; $1b
	const SPRITE_MIDDLE_AGED_WOMAN       ; $1c
	const SPRITE_BRUNETTE_GIRL           ; $1d
	const SPRITE_LANCE                   ; $1e
	const SPRITE_UNUSED_RED_1            ; $1f
	const SPRITE_SCIENTIST               ; $20
	const SPRITE_ROCKER                  ; $21
	const SPRITE_SWIMMER                 ; $22
	const SPRITE_SAFARI_ZONE_WORKER      ; $23
	const SPRITE_GYM_GUIDE               ; $24
	const SPRITE_GRAMPS                  ; $25
	const SPRITE_CLERK                   ; $26
	const SPRITE_FISHING_GURU            ; $27
	const SPRITE_GRANNY                  ; $28
	const SPRITE_NURSE                   ; $29
	const SPRITE_LINK_RECEPTIONIST       ; $2a
	const SPRITE_SILPH_PRESIDENT         ; $2b
	const SPRITE_SILPH_WORKER_M          ; $2c
	const SPRITE_WARDEN                  ; $2d
	const SPRITE_CAPTAIN                 ; $2e
	const SPRITE_FISHER                  ; $2f
	const SPRITE_KOGA                    ; $30
	const SPRITE_GUARD                   ; $31
	const SPRITE_UNUSED_RED_2            ; $32
	const SPRITE_MOM                     ; $33
	const SPRITE_BALDING_GUY             ; $34
	const SPRITE_LITTLE_BOY              ; $35
	const SPRITE_UNUSED_RED_3            ; $36
	const SPRITE_GAMEBOY_KID             ; $37
	const SPRITE_FAIRY                   ; $38
	const SPRITE_AGATHA                  ; $39
	const SPRITE_BRUNO                   ; $3a
	const SPRITE_LORELEI                 ; $3b
	const SPRITE_SEEL                    ; $3c
	const SPRITE_PIKACHU                 ; $3d
	const SPRITE_OFFICER_JENNY           ; $3e
	const SPRITE_SANDSHREW               ; $3f
	const SPRITE_ODDISH                  ; $40
	const SPRITE_BULBASAUR               ; $41
	const SPRITE_JIGGLYPUFF              ; $42
	const SPRITE_CLEFAIRY                ; $43
	const SPRITE_CHANSEY                 ; $44
	const SPRITE_JESSIE                  ; $45
	const SPRITE_JAMES                   ; $46
DEF FIRST_STILL_SPRITE EQU const_value
	const SPRITE_POKE_BALL               ; $47
	const SPRITE_FOSSIL                  ; $48
	const SPRITE_BOULDER                 ; $49
	const SPRITE_PAPER                   ; $4a
	const SPRITE_POKEDEX                 ; $4b
	const SPRITE_CLIPBOARD               ; $4c
	const SPRITE_SNORLAX                 ; $4d
	const SPRITE_UNUSED_OLD_AMBER        ; $4e
	const SPRITE_OLD_AMBER               ; $4f
	const SPRITE_UNUSED_GAMBLER_ASLEEP_1 ; $50
	const SPRITE_UNUSED_GAMBLER_ASLEEP_2 ; $51
	const SPRITE_GAMBLER_ASLEEP          ; $52
	const SPRITE_BASE_MON                ; $53
	const SPRITE_RAICHU                  ; $54
	const SPRITE_CHARIZARD               ; $55
	const SPRITE_BLASTOISE               ; $56
	const SPRITE_VENUSAUR                ; $57
	const SPRITE_IVYSAUR                 ; $58
	const SPRITE_CHARMANDER              ; $59
	const SPRITE_CHARMELEON              ; $5A
	const SPRITE_SQUIRTLE                ; $5B
	const SPRITE_WARTORTLE               ; $5C
	const SPRITE_PIDGEY                  ; $5D
	const SPRITE_PIDGEOTTO               ; $5E
	const SPRITE_PIDGEOT                 ; $5F
	const SPRITE_CATERPIE                ; $60
	const SPRITE_METAPOD                 ; $61
	const SPRITE_BUTTERFREE              ; $62
	const SPRITE_WEEDLE                  ; $63
	const SPRITE_KAKUNA                  ; $64
	const SPRITE_BEEDRILL                ; $65
	const SPRITE_RATTATA                 ; $66
	const SPRITE_RATICATE                ; $67
	const SPRITE_SPEAROW                 ; $68
	const SPRITE_FEAROW                  ; $69
	const SPRITE_EKANS                   ; $6A
	const SPRITE_ARBOK                   ; $6B
	const SPRITE_SANDSLASH               ; $6C
	const SPRITE_NIDORAN_F               ; $6D
	const SPRITE_NIDORINA                ; $6E
	const SPRITE_NIDOQUEEN               ; $6F
	const SPRITE_NIDORAN_M               ; $70
	const SPRITE_NIDORINO                ; $71
	const SPRITE_NIDOKING                ; $72
	const SPRITE_CLEFABLE                ; $73
	const SPRITE_VULPIX                  ; $74
	const SPRITE_NINETALES               ; $75
	const SPRITE_WIGGLYTUFF              ; $76
	const SPRITE_ZUBAT                   ; $77
	const SPRITE_GOLBAT                  ; $78
	const SPRITE_GLOOM                   ; $79
	const SPRITE_VILEPLUME               ; $7A
	const SPRITE_PARAS                   ; $7B
	const SPRITE_PARASECT                ; $7C
	const SPRITE_VENONAT                 ; $7D
	const SPRITE_VENOMOTH                ; $7E
	const SPRITE_DIGLETT                 ; $7F
	const SPRITE_DUGTRIO                 ; $80
	const SPRITE_MEOWTH                  ; $81
	const SPRITE_PERSIAN                 ; $82
	const SPRITE_PSYDUCK                 ; $83
	const SPRITE_GOLDUCK                 ; $84
	const SPRITE_MANKEY                  ; $85
	const SPRITE_PRIMEAPE                ; $86
	const SPRITE_GROWLITHE               ; $87
	const SPRITE_ARCANINE                ; $88
	const SPRITE_POLIWAG                 ; $89
	const SPRITE_POLIWHIRL               ; $8A
	const SPRITE_POLIWRATH               ; $8B
	const SPRITE_ABRA                    ; $8C
	const SPRITE_KADABRA                 ; $8D
	const SPRITE_ALAKAZAM                ; $8E
	const SPRITE_MACHOP                  ; $8F
	const SPRITE_MACHOKE                 ; $90
	const SPRITE_MACHAMP                 ; $91
	const SPRITE_BELLSPROUT              ; $92
	const SPRITE_WEEPINBELL              ; $93
	const SPRITE_VICTREEBEL              ; $94
	const SPRITE_TENTACOOL               ; $95
	const SPRITE_TENTACRUEL              ; $96
	const SPRITE_GEODUDE                 ; $97
	const SPRITE_GRAVELER                ; $98
	const SPRITE_GOLEM                   ; $99
	const SPRITE_PONYTA                  ; $9A
	const SPRITE_RAPIDASH                ; $9B
	const SPRITE_SLOWPOKE                ; $9C
	const SPRITE_SLOWBRO                 ; $9D
	const SPRITE_MAGNEMITE               ; $9E
	const SPRITE_MAGNETON                ; $9F
	const SPRITE_FARFETCHD               ; $A0
	const SPRITE_DODUO                   ; $A1
	const SPRITE_DODRIO                  ; $A2
	const SPRITE_DEWGONG                 ; $A3
	const SPRITE_GRIMER                  ; $A4
	const SPRITE_MUK                     ; $A5
	const SPRITE_SHELLDER                ; $A6
	const SPRITE_CLOYSTER                ; $A7
	const SPRITE_GASTLY                  ; $A8
	const SPRITE_HAUNTER                 ; $A9
	const SPRITE_GENGAR                  ; $AA
	const SPRITE_ONIX                    ; $AB
	const SPRITE_DROWZEE                 ; $AC
	const SPRITE_HYPNO                   ; $AD
	const SPRITE_KRABBY                  ; $AE
	const SPRITE_KINGLER                 ; $AF
	const SPRITE_VOLTORB                 ; $B0
	const SPRITE_ELECTRODE               ; $B1
	const SPRITE_EXEGGCUTE               ; $B2
	const SPRITE_EXEGGUTOR               ; $B3
	const SPRITE_CUBONE                  ; $B4
	const SPRITE_MAROWAK                 ; $B5
	const SPRITE_HITMONLEE               ; $B6
	const SPRITE_HITMONCHAN              ; $B7
	const SPRITE_LICKITUNG               ; $B8
	const SPRITE_KOFFING                 ; $B9
	const SPRITE_WEEZING                 ; $BA
	const SPRITE_RHYHORN                 ; $BB
	const SPRITE_RHYDON                  ; $BC
	const SPRITE_TANGELA                 ; $BD
	const SPRITE_KANGASKHAN              ; $BE
	const SPRITE_HORSEA                  ; $BF
	const SPRITE_SEADRA                  ; $C0
	const SPRITE_GOLDEEN                 ; $C1
	const SPRITE_SEAKING                 ; $C2
	const SPRITE_STARYU                  ; $C3
	const SPRITE_STARMIE                 ; $C4
	const SPRITE_MR_MIME                 ; $C5
	const SPRITE_SCYTHER                 ; $C6
	const SPRITE_JYNX                    ; $C7
	const SPRITE_ELECTABUZZ              ; $C8
	const SPRITE_MAGMAR                  ; $C9
	const SPRITE_PINSIR                  ; $CA
	const SPRITE_TAUROS                  ; $CB
	const SPRITE_MAGIKARP                ; $CC
	const SPRITE_GYARADOS                ; $CD
	const SPRITE_LAPRAS                  ; $CE
	const SPRITE_DITTO                   ; $CF
	const SPRITE_EEVEE                   ; $D0
	const SPRITE_VAPOREON                ; $D1
	const SPRITE_JOLTEON                 ; $D2
	const SPRITE_FLAREON                 ; $D3
	const SPRITE_PORYGON                 ; $D4
	const SPRITE_OMANYTE                 ; $D5
	const SPRITE_OMASTAR                 ; $D6
	const SPRITE_KABUTO                  ; $D7
	const SPRITE_KABUTOPS                ; $D8
	const SPRITE_AERODACTYL              ; $D9
	const SPRITE_ARTICUNO                ; $DA
	const SPRITE_ZAPDOS                  ; $DB
	const SPRITE_MOLTRES                 ; $DC
	const SPRITE_DRATINI                 ; $DD
	const SPRITE_DRAGONAIR               ; $DE
	const SPRITE_DRAGONITE               ; $DF
	const SPRITE_MEWTWO                  ; $E0
	const SPRITE_MEW                     ; $E1
DEF NUM_SPRITES EQU const_value - 1
