SECTION "NPC Sprites 1", ROMX

ScientistSprite::        INCBIN "gfx/sprites/scientist.2bpp"
RockerSprite::           INCBIN "gfx/sprites/rocker.2bpp"
SwimmerSprite::          INCBIN "gfx/sprites/swimmer.2bpp"
SafariZoneWorkerSprite:: INCBIN "gfx/sprites/safari_zone_worker.2bpp"
GymGuideSprite::         INCBIN "gfx/sprites/gym_guide.2bpp"
GrampsSprite::           INCBIN "gfx/sprites/gramps.2bpp"
ClerkSprite::            INCBIN "gfx/sprites/clerk.2bpp"
FishingGuruSprite::      INCBIN "gfx/sprites/fishing_guru.2bpp"
GrannySprite::           INCBIN "gfx/sprites/granny.2bpp"
NurseSprite::            INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSprite:: INCBIN "gfx/sprites/link_receptionist.2bpp"
SilphPresidentSprite::   INCBIN "gfx/sprites/silph_president.2bpp"
SilphWorkerMSprite::     INCBIN "gfx/sprites/silph_worker_m.2bpp"
WardenSprite::           INCBIN "gfx/sprites/warden.2bpp"
CaptainSprite::          INCBIN "gfx/sprites/captain.2bpp"
FisherSprite::           INCBIN "gfx/sprites/fisher.2bpp"
KogaSprite::             INCBIN "gfx/sprites/koga.2bpp"
GuardSprite::            INCBIN "gfx/sprites/guard.2bpp"
PokeBallSprite::         INCBIN "gfx/sprites/poke_ball.2bpp"
FossilSprite::           INCBIN "gfx/sprites/fossil.2bpp"
BoulderSprite::          INCBIN "gfx/sprites/boulder.2bpp"
PaperSprite::            INCBIN "gfx/sprites/paper.2bpp"
PokedexSprite::          INCBIN "gfx/sprites/pokedex.2bpp"
ClipboardSprite::        INCBIN "gfx/sprites/clipboard.2bpp"
SnorlaxSprite::          INCBIN "gfx/sprites/snorlax.2bpp"
OldAmberSprite::         INCBIN "gfx/sprites/old_amber.2bpp"
GamblerAsleepSprite::    INCBIN "gfx/sprites/gambler_asleep.2bpp"
QuestionMarkSprite::     INCBIN "gfx/sprites/question_mark.2bpp"


SECTION "NPC Sprites 2", ROMX

RedBikeSprite::          INCBIN "gfx/sprites/red_bike.2bpp"
RedSprite::              INCBIN "gfx/sprites/red.2bpp"
BlueSprite::             INCBIN "gfx/sprites/blue.2bpp"
OakSprite::              INCBIN "gfx/sprites/oak.2bpp"
YoungsterSprite::        INCBIN "gfx/sprites/youngster.2bpp"
MonsterSprite::          INCBIN "gfx/sprites/monster.2bpp"
CooltrainerFSprite::     INCBIN "gfx/sprites/cooltrainer_f.2bpp"
CooltrainerMSprite::     INCBIN "gfx/sprites/cooltrainer_m.2bpp"
LittleGirlSprite::       INCBIN "gfx/sprites/little_girl.2bpp"
BirdSprite::             INCBIN "gfx/sprites/bird.2bpp"
MiddleAgedManSprite::    INCBIN "gfx/sprites/middle_aged_man.2bpp"
GamblerSprite::          INCBIN "gfx/sprites/gambler.2bpp"
SuperNerdSprite::        INCBIN "gfx/sprites/super_nerd.2bpp"
GirlSprite::             INCBIN "gfx/sprites/girl.2bpp"
HikerSprite::            INCBIN "gfx/sprites/hiker.2bpp"
BeautySprite::           INCBIN "gfx/sprites/beauty.2bpp"
GentlemanSprite::        INCBIN "gfx/sprites/gentleman.2bpp"
;DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp"
BikerSprite::            INCBIN "gfx/sprites/biker.2bpp"
SailorSprite::           INCBIN "gfx/sprites/sailor.2bpp"
CookSprite::             INCBIN "gfx/sprites/cook.2bpp"
BikeShopClerkSprite::    INCBIN "gfx/sprites/bike_shop_clerk.2bpp"
MrFujiSprite::           INCBIN "gfx/sprites/mr_fuji.2bpp"
GiovanniSprite::         INCBIN "gfx/sprites/giovanni.2bpp"
RocketSprite::           INCBIN "gfx/sprites/rocket.2bpp"
ChannelerSprite::        INCBIN "gfx/sprites/channeler.2bpp"
;WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp"
SilphWorkerFSprite::     INCBIN "gfx/sprites/silph_worker_f.2bpp"
MiddleAgedWomanSprite::  INCBIN "gfx/sprites/middle_aged_woman.2bpp"
BrunetteGirlSprite::     INCBIN "gfx/sprites/brunette_girl.2bpp"
SeelSprite::             INCBIN "gfx/sprites/seel.2bpp"


SECTION "NPC Sprites 3", ROMX

OfficerJennySprite::     INCBIN "gfx/sprites/officer_jenny.2bpp"
PikachuSprite::          INCBIN "gfx/sprites/pikachu.2bpp"
SandshrewSprite::        INCBIN "gfx/sprites/sandshrew.2bpp"
OddishSprite::           INCBIN "gfx/sprites/oddish.2bpp"
BulbasaurSprite::        INCBIN "gfx/sprites/bulbasaur.2bpp"
JigglypuffSprite::       INCBIN "gfx/sprites/jigglypuff.2bpp"
ClefairySprite::         INCBIN "gfx/sprites/clefairy.2bpp"
ChanseySprite::          INCBIN "gfx/sprites/chansey.2bpp"
SurfingPikachuSprite::   INCBIN "gfx/sprites/surfing_pikachu.2bpp"
JessieSprite::           INCBIN "gfx/sprites/jessie.2bpp"
JamesSprite::            INCBIN "gfx/sprites/james.2bpp"


SECTION "NPC Sprites 4", ROMX

DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp"
WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp"
LanceSprite::            INCBIN "gfx/sprites/lance.2bpp"
MomSprite::              INCBIN "gfx/sprites/mom.2bpp"
BaldingGuySprite::       INCBIN "gfx/sprites/balding_guy.2bpp"
LittleBoySprite::        INCBIN "gfx/sprites/little_boy.2bpp"
GameboyKidSprite::       INCBIN "gfx/sprites/gameboy_kid.2bpp"
FairySprite::            INCBIN "gfx/sprites/fairy.2bpp"
AgathaSprite::           INCBIN "gfx/sprites/agatha.2bpp"
BrunoSprite::            INCBIN "gfx/sprites/bruno.2bpp"
LoreleiSprite::          INCBIN "gfx/sprites/lorelei.2bpp"


SECTION "Follower Sprites", ROMX

BaseMonSprite::          INCBIN "gfx/sprites/base_mon.2bpp"
RaichuSprite::           INCBIN "gfx/sprites/raichu.2bpp"
CharizardSprite::        INCBIN "gfx/sprites/charizard.2bpp"
BlastoiseSprite::        INCBIN "gfx/sprites/blastoise.2bpp"
VenusaurSprite::         INCBIN "gfx/sprites/venusaur.2bpp"
IvysaurSprite::          INCBIN "gfx/sprites/ivysaur.2bpp"
CharmanderSprite::       INCBIN "gfx/sprites/charmander.2bpp"
CharmeleonSprite::       INCBIN "gfx/sprites/charmeleon.2bpp"
SquirtleSprite::         INCBIN "gfx/sprites/squirtle.2bpp"
WartortleSprite::        INCBIN "gfx/sprites/wartortle.2bpp"
PidgeySprite::           INCBIN "gfx/sprites/pidgey.2bpp"
PidgeottoSprite::        INCBIN "gfx/sprites/pidgeotto.2bpp"
PidgeotSprite::          INCBIN "gfx/sprites/pidgeot.2bpp"
CaterpieSprite::         INCBIN "gfx/sprites/caterpie.2bpp"
MetapodSprite::          INCBIN "gfx/sprites/metapod.2bpp"
ButterfreeSprite::       INCBIN "gfx/sprites/butterfree.2bpp"
WeedleSprite::           INCBIN "gfx/sprites/weedle.2bpp"
KakunaSprite::           INCBIN "gfx/sprites/kakuna.2bpp"
BeedrillSprite::         INCBIN "gfx/sprites/beedrill.2bpp"
RattataSprite::          INCBIN "gfx/sprites/rattata.2bpp"
RaticateSprite::         INCBIN "gfx/sprites/raticate.2bpp"
SpearowSprite::          INCBIN "gfx/sprites/spearow.2bpp"
FearowSprite::           INCBIN "gfx/sprites/fearow.2bpp"
EkansSprite::            INCBIN "gfx/sprites/ekans.2bpp"
ArbokSprite::            INCBIN "gfx/sprites/arbok.2bpp"
SandslashSprite::        INCBIN "gfx/sprites/sandslash.2bpp"
NidoranFSprite::         INCBIN "gfx/sprites/nidoran_f.2bpp"
NidorinaSprite::         INCBIN "gfx/sprites/nidorina.2bpp"
NidoqueenSprite::        INCBIN "gfx/sprites/nidoqueen.2bpp"
NidoranMSprite::         INCBIN "gfx/sprites/nidoran_m.2bpp"
NidorinoSprite::         INCBIN "gfx/sprites/nidorino.2bpp"
NidokingSprite::         INCBIN "gfx/sprites/nidoking.2bpp"

SECTION "Follower Sprites 2", ROMX

ClefableSprite::         INCBIN "gfx/sprites/clefable.2bpp"
VulpixSprite::           INCBIN "gfx/sprites/vulpix.2bpp"
NinetalesSprite::        INCBIN "gfx/sprites/ninetales.2bpp"
WigglytuffSprite::       INCBIN "gfx/sprites/wigglytuff.2bpp"
ZubatSprite::            INCBIN "gfx/sprites/zubat.2bpp"
GolbatSprite::           INCBIN "gfx/sprites/golbat.2bpp"
GloomSprite::            INCBIN "gfx/sprites/gloom.2bpp"
VileplumeSprite::        INCBIN "gfx/sprites/vileplume.2bpp"
ParasSprite::            INCBIN "gfx/sprites/paras.2bpp"
ParasectSprite::         INCBIN "gfx/sprites/parasect.2bpp"
VenonatSprite::          INCBIN "gfx/sprites/venonat.2bpp"
VenomothSprite::         INCBIN "gfx/sprites/venomoth.2bpp"
DiglettSprite::          INCBIN "gfx/sprites/diglett.2bpp"
DugtrioSprite::          INCBIN "gfx/sprites/dugtrio.2bpp"
MeowthSprite::           INCBIN "gfx/sprites/meowth.2bpp"
PersianSprite::          INCBIN "gfx/sprites/persian.2bpp"
PsyduckSprite::          INCBIN "gfx/sprites/psyduck.2bpp"
GolduckSprite::          INCBIN "gfx/sprites/golduck.2bpp"
MankeySprite::           INCBIN "gfx/sprites/mankey.2bpp"
PrimeapeSprite::         INCBIN "gfx/sprites/primeape.2bpp"
GrowlitheSprite::        INCBIN "gfx/sprites/growlithe.2bpp"
ArcanineSprite::         INCBIN "gfx/sprites/arcanine.2bpp"
PoliwagSprite::          INCBIN "gfx/sprites/poliwag.2bpp"
PoliwhirlSprite::        INCBIN "gfx/sprites/poliwhirl.2bpp"
PoliwrathSprite::        INCBIN "gfx/sprites/poliwrath.2bpp"
AbraSprite::             INCBIN "gfx/sprites/abra.2bpp"
KadabraSprite::          INCBIN "gfx/sprites/kadabra.2bpp"
AlakazamSprite::         INCBIN "gfx/sprites/alakazam.2bpp"
MachopSprite::           INCBIN "gfx/sprites/machop.2bpp"
MachokeSprite::          INCBIN "gfx/sprites/machoke.2bpp"
MachampSprite::          INCBIN "gfx/sprites/machamp.2bpp"
BellsproutSprite::       INCBIN "gfx/sprites/bellsprout.2bpp"
WeepinbellSprite::       INCBIN "gfx/sprites/weepinbell.2bpp"
VictreebelSprite::       INCBIN "gfx/sprites/victreebel.2bpp"
TentacoolSprite::        INCBIN "gfx/sprites/tentacool.2bpp"
TentacruelSprite::       INCBIN "gfx/sprites/tentacruel.2bpp"
GeodudeSprite::          INCBIN "gfx/sprites/geodude.2bpp"
GravelerSprite::         INCBIN "gfx/sprites/graveler.2bpp"
GolemSprite::            INCBIN "gfx/sprites/golem.2bpp"
PonytaSprite::           INCBIN "gfx/sprites/ponyta.2bpp"
RapidashSprite::         INCBIN "gfx/sprites/rapidash.2bpp"

SECTION "Follower Sprites 3", ROMX

SlowpokeSprite::         INCBIN "gfx/sprites/slowpoke.2bpp"
SlowbroSprite::          INCBIN "gfx/sprites/slowbro.2bpp"
MagnemiteSprite::        INCBIN "gfx/sprites/magnemite.2bpp"
MagnetonSprite::         INCBIN "gfx/sprites/magneton.2bpp"
FarfetchdSprite::        INCBIN "gfx/sprites/farfetch_d.2bpp"
DoduoSprite::            INCBIN "gfx/sprites/doduo.2bpp"
DodrioSprite::           INCBIN "gfx/sprites/dodrio.2bpp"
DewgongSprite::          INCBIN "gfx/sprites/dewgong.2bpp"
GrimerSprite::           INCBIN "gfx/sprites/grimer.2bpp"
MukSprite::              INCBIN "gfx/sprites/muk.2bpp"
ShellderSprite::         INCBIN "gfx/sprites/shellder.2bpp"
CloysterSprite::         INCBIN "gfx/sprites/cloyster.2bpp"
GastlySprite::           INCBIN "gfx/sprites/gastly.2bpp"
HaunterSprite::          INCBIN "gfx/sprites/haunter.2bpp"
GengarSprite::           INCBIN "gfx/sprites/gengar.2bpp"
OnixSprite::             INCBIN "gfx/sprites/onix.2bpp"
DrowzeeSprite::          INCBIN "gfx/sprites/drowzee.2bpp"
HypnoSprite::            INCBIN "gfx/sprites/hypno.2bpp"
KrabbySprite::           INCBIN "gfx/sprites/krabby.2bpp"
KinglerSprite::          INCBIN "gfx/sprites/kingler.2bpp"
VoltorbSprite::          INCBIN "gfx/sprites/voltorb.2bpp"
ElectrodeSprite::        INCBIN "gfx/sprites/electrode.2bpp"
ExeggcuteSprite::        INCBIN "gfx/sprites/exeggcute.2bpp"
ExeggutorSprite::        INCBIN "gfx/sprites/exeggutor.2bpp"
CuboneSprite::           INCBIN "gfx/sprites/cubone.2bpp"
MarowakSprite::          INCBIN "gfx/sprites/marowak.2bpp"


SECTION "Follower Sprites 4", ROMX

HitmonleeSprite::        INCBIN "gfx/sprites/hitmonlee.2bpp"
HitmonchanSprite::       INCBIN "gfx/sprites/hitmonchan.2bpp"
LickitungSprite::        INCBIN "gfx/sprites/lickitung.2bpp"
KoffingSprite::          INCBIN "gfx/sprites/koffing.2bpp"
WeezingSprite::          INCBIN "gfx/sprites/weezing.2bpp"
RhyhornSprite::          INCBIN "gfx/sprites/rhyhorn.2bpp"
RhydonSprite::           INCBIN "gfx/sprites/rhydon.2bpp"
TangelaSprite::          INCBIN "gfx/sprites/tangela.2bpp"
KangaskhanSprite::       INCBIN "gfx/sprites/kangaskhan.2bpp"
HorseaSprite::           INCBIN "gfx/sprites/horsea.2bpp"
SeadraSprite::           INCBIN "gfx/sprites/seadra.2bpp"
GoldeenSprite::          INCBIN "gfx/sprites/goldeen.2bpp"
SeakingSprite::          INCBIN "gfx/sprites/seaking.2bpp"
StaryuSprite::           INCBIN "gfx/sprites/staryu.2bpp"
StarmieSprite::          INCBIN "gfx/sprites/starmie.2bpp"
MrMimeSprite::           INCBIN "gfx/sprites/mr_mime.2bpp"
ScytherSprite::          INCBIN "gfx/sprites/scyther.2bpp"
JynxSprite::             INCBIN "gfx/sprites/jynx.2bpp"
ElectabuzzSprite::       INCBIN "gfx/sprites/electabuzz.2bpp"
MagmarSprite::           INCBIN "gfx/sprites/magmar.2bpp"
PinsirSprite::           INCBIN "gfx/sprites/pinsir.2bpp"
TaurosSprite::           INCBIN "gfx/sprites/tauros.2bpp"
MagikarpSprite::         INCBIN "gfx/sprites/magikarp.2bpp"
GyaradosSprite::         INCBIN "gfx/sprites/gyarados.2bpp"
LaprasSprite::           INCBIN "gfx/sprites/lapras.2bpp"
DittoSprite::            INCBIN "gfx/sprites/ditto.2bpp"
EeveeSprite::            INCBIN "gfx/sprites/eevee.2bpp"
VaporeonSprite::         INCBIN "gfx/sprites/vaporeon.2bpp"
JolteonSprite::          INCBIN "gfx/sprites/jolteon.2bpp"
FlareonSprite::          INCBIN "gfx/sprites/flareon.2bpp"
PorygonSprite::          INCBIN "gfx/sprites/porygon.2bpp"
OmanyteSprite::          INCBIN "gfx/sprites/omanyte.2bpp"
OmastarSprite::          INCBIN "gfx/sprites/omastar.2bpp"


SECTION "Follower Sprites 5", ROMX

KabutoSprite::           INCBIN "gfx/sprites/kabuto.2bpp"
KabutopsSprite::         INCBIN "gfx/sprites/kabutops.2bpp"
AerodactylSprite::       INCBIN "gfx/sprites/aerodactyl.2bpp"
ArticunoSprite::         INCBIN "gfx/sprites/articuno.2bpp"
ZapdosSprite::           INCBIN "gfx/sprites/zapdos.2bpp"
MoltresSprite::          INCBIN "gfx/sprites/moltres.2bpp"
DratiniSprite::          INCBIN "gfx/sprites/dratini.2bpp"
DragonairSprite::        INCBIN "gfx/sprites/dragonair.2bpp"
DragoniteSprite::        INCBIN "gfx/sprites/dragonite.2bpp"
MewtwoSprite::           INCBIN "gfx/sprites/mewtwo.2bpp"
MewSprite::              INCBIN "gfx/sprites/mew.2bpp"